FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

#FROM microsoft/dotnet:2.1-runtime-nanoserver-1809
#FROM mcr.microsoft.com/dotnet/core/runtime:2.1
FROM mcr.microsoft.com/dotnet/core/aspnet:2.1

WORKDIR /app
COPY --from=build-env /app/out ./

EXPOSE 80

ENTRYPOINT ["dotnet", "SensorHubModule.dll"]